"""Extra unique sections so each guide clears 1,500 words."""

MORE = {
"arsenal-vs-leeds-10-oct-2026-preview": {
"excerpt": "Arsenal host Leeds on 10 October 2026 at 12:30 BST (17:00 IST) at the Emirates Stadium. TNT Sports in the UK, plus the India watch path.",
"h2": "How to use this page on the Friday before",
"paras": [
"The useful Friday routine is short. Open the Premier League fixture page and confirm 12:30 has not moved. Open JioHotstar or the Star Sports guide and search Arsenal, not just “Premier League”, because the 17:30 United game will dominate the thumbnails. Then write two further alarms you will not keep inside this match: Wednesday 00:30 IST for Lille, and Sunday 18 October 21:00 IST for Forest. People lose the Leeds game not because the preview was thin but because they stored it as “Arsenal Saturday” and opened the stream at 22:00 out of habit.",
"If you are taking someone to their first Emirates lunchtime, the football advice is separate from the travel advice. We still will not quote a ticket price. We will say that 12:30 BST punishes a late Piccadilly line connection, and that television viewers in India have the easier version of the same match. Either way, the team sheet is a club post around an hour before kick-off. A graphic with invented shirt numbers is not a kindness to a new supporter.",
],
},
"leeds-vs-man-united-18-oct-2026-preview": {
"excerpt": "Leeds host Manchester United on 18 October 2026 at 14:00 BST (18:30 IST) at Elland Road. Sky Sports in the UK, plus the India watch path.",
"h2": "A full Sunday for anyone following both Leeds games",
"paras": [
"Leeds’ October is easier to follow if you write it as two away-and-home lines rather than as “United week”. On 10 October they are the away side at the Emirates at 12:30 BST, on TNT, which is 17:00 IST. On 18 October they are the home side at Elland Road at 14:00 BST, on Sky, which is 18:30 IST. Eight days, two broadcasters in Britain, one Indian rights package that covers both because the rights are for the league. A Leeds supporter in India does not need two subscriptions. A Leeds supporter in Britain might. That split is the practical point Radio Times’ channel split is there to explain.",
"United’s side of the same fortnight is louder and easier to mix up. Old Trafford against Tottenham is 10 October at 17:30 BST. The Metropolitano against Atlético is 13 October, 00:30 IST on the 14th. Elland Road is the 18th. If a highlights show says “United conceded at home”, ask which ground. Old Trafford and Elland Road are both “United” in a careless sentence and only one of them is this match.",
"On the day itself, Indian viewers can treat 18:15 IST as the login time and 20:45 IST as the handover toward Forest vs Arsenal at 21:00, if they want both Sky games. You do not have to. The football reason to stay with Elland Road until the end is that 14:00 kick-offs often change after the hour, when legs from the European week show. Whether they do is the match’s business. Predicting the minute is not.",
"Publishers who syndicate this guide should keep “Elland Road” in the title and in the FAQ answer to “where”. The most common bad snippet is a correct 18:30 IST attached to Old Trafford, copied from the Tottenham preview. Our schema location is Leeds. If you rewrite the page, do not let a template from a different United match fill the venue field. That single bug is how a whole weekend of search traffic lands on the wrong ground.",
],
},
"nottingham-forest-vs-arsenal-18-oct-2026": {
"excerpt": "Nottingham Forest host Arsenal on 18 October 2026 at 16:30 BST (21:00 IST) at the City Ground. Sky Sports in the UK, with India notes.",
"h2": "Why the City Ground date is its own search",
"paras": [
"People search “Arsenal fixture” and receive a list. The list that matters on this Sunday is the one that says Nottingham, 16:30 BST, Sky. The Emirates lunchtime against Leeds is already played by then. Lille in the Champions League is the Tuesday in between. Bayern in Munich is the Wednesday after. A supporter who only saves “Arsenal” will open the wrong broadcaster or the wrong country. Write Forest in the calendar title even if you support Arsenal. The home team is how the Premier League file names the match, and it is how the Indian app sorts it.",
"The Trent is not a detail for colour. The City Ground sits by the river, and a 16:30 Sunday in mid-October is a lights game more often than a sunshine game. We are not giving a weather forecast. We are saying that television pictures from this ground look different from the Emirates pictures of the previous Saturday, and that anyone writing a caption should not reuse an Emirates photo. Our own card for this page is a self-hosted graphic with the IST time, not a stock stadium shot.",
"For the viewer who has already watched Leeds vs United at 18:30 IST, the break before 21:00 is long enough to eat and short enough to miss team news. Check the Forest and Arsenal channels at 20:30 IST. If a player who started against Lille is absent, that is a fact from the sheet, not a rumour this preview is allowed to invent in September. The same rule applies to Forest’s side. We do not have it.",
"One more clock, because this is the last 16:30 BST Super Sunday before the change. On 1 November, Liverpool vs Arsenal is 16:30 GMT and therefore 22:00 IST. If you build a personal rule that “4:30pm England means 9pm India”, you will be right for this Forest match and wrong a fortnight later. Teach the calendar the letters BST and GMT, not a permanent offset. That is the whole trick of October 2026.",
],
},
"chelsea-vs-man-united-31-oct-2026-preview": {
"excerpt": "Chelsea host Manchester United on 31 October 2026 at 12:30 GMT (18:00 IST) at Stamford Bridge. TNT Sports in the UK, India notes included.",
"h2": "Halloween on the fixture list, not in the preview",
"paras": [
"31 October will attract costume headlines. The football facts are duller and more useful. Stamford Bridge, 12:30 GMT, TNT Sports, 18:00 IST, United the visitors, Tottenham already played here on the 24th at a different hour on a different broadcaster. If a social card adds Halloween graphics and drops the letters GMT, it has kept the joke and lost the information. We are leaving the joke out.",
"The same evening in Europe is the Klassiker at 18:30 CET, 23:00 IST, and then the Milan derby at 20:45 CET, 01:15 IST Sunday. A household that wants Chelsea and also wants Bayern vs Dortmund can do both, with a gap. A household that wants Chelsea and the derby needs to stay up. None of those matches share a ball. They share a date. Put the home team in the alarm name or you will sit down for Munich and find Fulham on the screen, or the reverse.",
"United’s week either side is Bournemouth at Old Trafford on Sunday 25 October at 14:00 GMT, this lunchtime at the Bridge, and Roma at Old Trafford on Tuesday 3 November at 21:00 CET. Three competitions’ worth of travel if you count Europe, two countries, one squad. The manager will be asked who is rested. The answer is not on this page because it does not exist yet. What can be planned now is the Indian evening: 18:00 start, full time around 20:00, room afterwards.",
"US readers get a different kindness. 8:30am EDT is early, but it is still daylight time. The clocks in the US go back overnight into Sunday. If you record the match and watch it Sunday morning, do not be surprised that the phone’s zone label has changed while the recording’s kick-off has not. The whistle was 12:30 GMT. That UTC instant does not move when a phone updates.",
],
},
"liverpool-vs-arsenal-1-nov-2026-preview": {
"excerpt": "Liverpool host Arsenal on 1 November 2026 at 16:30 GMT (22:00 IST) at Anfield. Sky Sports Super Sunday, with India watch notes and no betting.",
"h2": "The weekend this match actually sits inside",
"paras": [
"Saturday 31 October is Chelsea vs Manchester United at lunchtime and, in other leagues, Bayern vs Dortmund and the Milan derby. Sunday 1 November opens with Aston Villa vs Fulham at 14:00 GMT, 19:30 IST, on Sky, and then this Anfield game at 22:00 IST. Monday 2 November is Newcastle vs Everton at 20:00 GMT, 01:30 IST Tuesday, also on Sky according to the Premier League notice. If you only circle Anfield you will still collide with the rest of the weekend the moment you open a live scores app. Knowing the neighbours stops you treating a Villa goal notification as an Arsenal goal.",
"Arsenal’s route in is Forest on 18 October, Bayern on 21 October, the league matches in between that the table will show, and then Anfield. Liverpool’s route in is Villarreal at home on 20 October and the league games around it, then Arsenal, then Fenerbahçe on 4 November. Both clubs are in a European sandwich. Commentators will say so. A preview written before those European games are played should not pretend to know who came through them healthy. Leave a blank where the injury list will go.",
"For Indian viewers, 22:00 is the latest of the familiar Super Sunday hours this autumn. Food, transport and Monday morning all sit closer to the final whistle than they did for a 21:00 October kick-off. If you are watching with children or with an early shift, decide on the replay before kick-off, using JioHotstar’s own catch-up if it is in the package. We will not link a third-party upload.",
"The phrase “champions Arsenal” in Sky’s TV copy is a label for the title they carried into the season. By 1 November it may still be a fair description of the holders and a bad description of the table. Open premierleague.com that morning. If you quote a points gap, quote it from there with the time you checked. This article will stay silent on the number so it cannot go stale in a dangerous way. Stale clocks are worse than stale tables, but both travel.",
],
},
"nottingham-forest-vs-man-city-7-nov-2026": {
"excerpt": "Nottingham Forest host Manchester City on 7 November 2026 at 17:30 GMT (23:00 IST) at the City Ground. Sky Sports in the UK, India watch notes.",
"h2": "A late Saturday that runs into Sunday",
"paras": [
"23:00 IST on a Saturday is a different promise from 21:00. Kick-off at the City Ground is 17:30 GMT. Ninety minutes plus a long stoppage page takes the end of the match past midnight in India. Tell the group chat that before they agree to “watch City”. People who have to travel on Sunday morning should know the shape of the night. The Premier League did not pick 17:30 to suit Kolkata. The conversion is our job, and the honest conversion includes the finish, not only the start.",
"Earlier that Saturday, Leeds vs Tottenham is 12:30 GMT on TNT, 18:00 IST. It is a perfectly watchable game and a different subscription in Britain. In India both can sit inside the Premier League rights, but they are not one continuous programme. Log out of the idea that “Saturday Premier League” is a single stream you leave on. Search Forest when 22:30 IST arrives. City’s trip to Leipzig on 4 November is the European context, three days before, at 01:30 IST on the 5th if the 21:00 CET listing holds. How many of those players start at the City Ground is a Saturday question.",
"Sunday 8 November then piles up: several 14:00 GMT games and United vs Aston Villa at 16:30 GMT, 22:00 IST. Forest vs City is the Saturday night door into that Sunday. You can skip all of it. You cannot claim you were surprised by the congestion if you read the Premier League’s November notice, which is where these times come from. We have not added matches that notice does not list.",
"Ground reminder, because Forest appear twice in this batch. Arsenal on 18 October was 16:30 BST, 21:00 IST, a Super Sunday. City on 7 November is 17:30 GMT, 23:00 IST, a Saturday night. Same City Ground, different week, different British zone, different Indian hour, different opponent. If your notes say “Forest home, 9pm”, they are only right for Arsenal. City is 11pm. Fix the note now.",
],
},
"barcelona-vs-real-madrid-clasico-25-oct-2026": {
"excerpt": "Barcelona host Real Madrid on 25 October 2026 at Spotify Camp Nou. Clubs list 21:00 CEST (00:30 IST on 26 Oct). Clock-change caveat, FanCode in India.",
"h2": "What to send in the group chat, and what to hold back",
"paras": [
"Send this: Sunday 25 October, Spotify Camp Nou, Barcelona at home, Real Madrid away, clubs said 21:00 CEST on 1 September. Hold this until La Liga repeats it after the clocks change: the IST minute. If you must tell family when to sit down, say “after midnight India, confirm Saturday”. That sentence is less satisfying than a single number and much harder to get wrong. The two candidate numbers are 00:30 IST and 01:30 IST on Monday 26 October. They are not a range. They are two different readings of a label that may be updated.",
"The football week either side is solid even while the minute is soft. PSG vs Barcelona is Tuesday 20 October, 00:30 IST Wednesday. Real Madrid vs Leipzig is Wednesday 21 October, 00:30 IST Thursday. Then this domestic night. Then, for Barcelona, Aston Villa at Camp Nou on Tuesday 3 November at 21:00 CET, 01:30 IST Wednesday. A supporter who thinks the Clásico is the end of the month is right about the league and wrong about Europe. Villa are the next Camp Nou night that is already on the club calendar.",
],
},
"ac-milan-vs-inter-31-oct-2026-derby": {
"excerpt": "AC Milan host Inter on 31 October 2026 at 20:45 CET (01:15 IST on 1 November) at San Siro. Serie A derby, Italy TV notes, India app to confirm.",
"h2": "Sharing San Siro, and not sharing a kick-off with Munich",
"paras": [
"San Siro hosts both Milan clubs, so “the Milan derby at San Siro” is not a riddle about which ground. It is a riddle about which bench is the home bench. AC Milan are at home on 31 October. Inter’s fixture list says so by listing Milan vs Inter. If a stream title reverses the names, you are on a different edit or a different match. Look for the home side on the left in the Italian convention, and do not be shy about reading the competition bug: Serie A, not the Champions League.",
"Bayern vs Dortmund kick off at 18:30 CET the same evening, two hours earlier, 23:00 IST. You can watch the first half in Munich and still be there for the start in Milan only if you leave the Klassiker. You cannot watch both live in full. Choose before 22:30 IST rather than during added time, when the illegal second stream looks tempting. It is not a plan. A legal replay the next day is a plan, if the app you pay for offers one. We have not verified a specific replay button, so look for it yourself inside the licensed service.",
"The derby’s place in Inter’s month is after a European autumn that includes Club Brugge at home on 13 October and continues through the league-phase dates UEFA has already published. Milan’s trip to Bournemouth in the Europa League is 22 October, nine days before this derby, at 00:30 IST on the 23rd. That south-coast game is a separate preview. It explains why Italian reporters will ask about travel. It does not name the derby XI.",
"For anyone awake at 01:15 IST, the US east is still on Saturday afternoon, 3:45pm EDT. Friends in New York and friends in Jaipur are not watching “tomorrow” and “tonight” in the same way. Say both dates when you invite them. Sunday 01:15 IST is Saturday 20:45 CET is Saturday 3:45pm EDT. Three labels, one whistle. The FAQ on this page uses the Indian one first because that is the audience most likely to mis-file the date.",
],
},
"juventus-vs-napoli-1-nov-2026-preview": {
"excerpt": "Juventus host Napoli on 1 November 2026 at 20:45 CET (01:15 IST, 2 November) at Allianz Stadium, Turin. DAZN in Italy; India app to confirm.",
"h2": "Napoli’s other October date, so you do not merge them",
"paras": [
"Napoli vs Roma is Saturday 24 October at 18:00 local, and that Saturday is still CEST, so 21:30 IST. It is in Naples. Juventus vs Napoli is Sunday 1 November at 20:45 CET, 01:15 IST Monday, in Turin. Same club, different week, different zone letter, different ground. A search for “Napoli kick-off” in late October will offer both. Read the opponent. Roma means Naples and an early Indian evening. Juventus means Turin and a Monday small hours start.",
"Porto vs Napoli in the Champions League is 4 November in the evening wave, three days after Turin. If Napoli look tired on Sunday, the Porto date is the fair question for a reporter. It is not a reason for us to list a rotated team in advance. Juventus, meanwhile, have a Europa League trail that includes the trip to Celta Vigo on 15 October. By 1 November that match is history. We will not invent its effect.",
"Indian viewers who watched the Milan derby at 01:15 IST on Sunday and Anfield at 22:00 IST on Sunday are being asked for a third late night on Monday. That is a lot of football and a bad plan if Monday is a working day. Pick one Italian game if you must pick. The derby has the shared city. This one has the two clubs whose league meetings move the title conversation in most seasons. We are not saying which is “bigger”. We are saying they are 24 hours apart and both end after 1am India time.",
"Allianz Stadium is Juventus’s ground. It is not the Delle Alpi, which is the old site people still mention, and it is not San Siro. If a map pin looks wrong, trust the club name and the city of Turin. Ticket buying stays on the club’s site. Nothing in this preview is an offer of a seat, a price, or a travel package. The schema location says Allianz Stadium, Turin, Italy, which is as specific as the sources allow.",
],
},
"bayern-vs-dortmund-31-oct-2026-klassiker": {
"excerpt": "Bayern host Dortmund on 31 October 2026 at 18:30 CET (23:00 IST) at the Allianz Arena. Bundesliga Klassiker, with India and US channels still to confirm.",
"h2": "Der Klassiker without a fake head-to-head",
"paras": [
"Bundesliga.com’s season piece is happy to call this the fixture fans look up first, and it reminds readers that the clubs met in the Supercup on 22 August. Use those two dates as anchors: August was a cup, 31 October is the league. Do not quote a “last five meetings” line unless you have the league’s own table in front of you and you cite it. We do not, in this article, so we do not. The reputation of the fixture is enough to explain the search traffic. Invented numbers would explain a later correction.",
"Bayern’s European neighbours are Arsenal at home on 21 October and Atlético away on 3 November. Dortmund’s Matchday 4 game is at home to Real Betis on 4 November. The Klassiker is the Saturday between those European assignments. Squad lists on the Friday will be the news. Until Friday, any XI is fiction, including a well-designed one. If you run a site that auto-fills “predicted lineups”, turn that module off for this slug. Empty is more accurate.",
"India’s channel is deliberately blank. Naming Sony or Zee because one of them has been right in a previous season would be a guess, and a guess on a watch page is the sentence people screenshot. Check midweek. If you find the tile, the rest of this guide — 18:30 CET, 23:00 IST, Allianz Arena, Bayern at home — still stands. The pictures move. The clock does not, unless the Bundesliga moves it.",
"US afternoon, 1:30pm EDT, is a friendly hour if a network has the match. Indian 23:00 is not, especially with the Milan derby starting at 01:15 IST while Munich may still be in added time. Decide which crest you are following. Both matches are real, both are licensed somewhere, and neither requires a second shady tab. One screen, one legal login, one whistle.",
],
},
"real-madrid-vs-leipzig-ucl-21-oct-2026": {
"excerpt": "Real Madrid host RB Leipzig on 21 October 2026 in the Champions League, 21:00 CEST (00:30 IST on 22 Oct) at the Bernabéu. SonyLIV in India.",
"h2": "The Wednesday list, written in IST order",
"paras": [
"Tuesday 20 October’s 21:00 CEST wave becomes Wednesday 00:30 IST and includes PSG vs Barcelona, Liverpool vs Villarreal and Manchester City vs AEK. Sleep, then Wednesday 21 October’s 21:00 CEST wave becomes Thursday 00:30 IST and includes this Bernabéu game and Bayern vs Arsenal. If you support Madrid and Arsenal, Thursday is a choice. If you support Madrid only, Thursday is simple: Leipzig, not the Clásico. The Clásico is Sunday 25 October at Camp Nou, with the daylight-saving caveat explained on that page.",
"Mourinho’s name is in Barcelona’s Clásico article as the Madrid coach. That is a source, not a full biography, and it is not a warranty that the same coach will be in the dugout if something changes before the 21st. Check the club site that week. Leipzig’s coach is not named in the schedule sources we used, so we do not name one. The same restraint applies to every player. The sheet is an hour before kick-off.",
"A Bernabéu European night on television is a good test of whether your stream is the legal one. The official pictures carry the UEFA bug and the Sony or TNT bug depending on the country. A stream with a different scoreboard layout and a chat overlay is not “the same pictures”. Close it. The match will be there on SonyLIV for Indian accounts, on TNT in Britain, and on Paramount+ in the US, subject to the usual “confirm the tile” line because production bugs move.",
"After the match, do not let a highlight package rename it El Clásico because both Spanish giants are in the news that week. Leipzig are the visitors. The return fixture in this league phase is not a second leg next week. It is a different matchday, later, and it is not this page. One opponent, one date, one IST midnight.",
"A last practical note for people who record rather than watch live. Thursday 00:30 IST means the file should be labelled 22 October in India and 21 October in Madrid. Players who search their own library the next morning will look up the wrong day if you only stored “Wednesday”. Put both dates in the recording title. The same habit saves the Clásico, which also crosses midnight. Two Spanish club nights in one week, two date-line crossings, zero excuse for a calendar that only knows one timezone.",
],
},
"man-united-vs-roma-ucl-3-nov-2026": {
"excerpt": "Manchester United host Roma on 3 November 2026 in the Champions League, 21:00 CET (01:30 IST on 4 Nov) at Old Trafford. SonyLIV notes, no betting.",
"h2": "Old Trafford in November, after the clocks",
"paras": [
"United’s home European night against Roma is easy to file next to the October trip to Atlético and then mis-time. Atlético was 21:00 CEST, 00:30 IST. Roma is 21:00 CET, 01:30 IST. The face of the European clock says 21:00 both times. India does not. If your phone still has a recurring event called “United UCL 12:30am”, delete it and make a new one for 4 November at 01:30. Recurring events are how clock-change weekends go wrong.",
"The league match four days earlier is Chelsea away, 31 October, 12:30 GMT, 18:00 IST, on TNT in Britain. Then this, on TNT as well if you are in the UK, because European nights are TNT’s, while the Chelsea league game is also TNT’s lunchtime selection. A UK viewer might be on the same broadcaster for both. An Indian viewer is not: Premier League on JioHotstar, Champions League on SonyLIV. Two apps, two logins, one club. Set them up on the Tuesday afternoon, not at 01:20 IST.",
"Roma arrive from a Matchday 2 night that was their own home game against Real Madrid, 14 October, Stadio Olimpico. They are not “the team who just played Madrid” in any selection sense we can prove from a September desk. They are the team whose October home date was Madrid and whose November away date is United. That is the whole factual link. It is enough to explain why both club names are already in people’s search history.",
"Same-whistle alternatives are Barcelona vs Aston Villa and Atlético vs Bayern. If the house is divided, the legal answer is still one feed per login. Highlights on SonyLIV the next day cover the games you did not choose. There is no sporting duty to watch three matches badly. Watch Old Trafford properly or watch Madrid properly. The previews exist so the choice is informed, not so that anyone stays up for all of them.",
"One more United trap sits on the following weekend, outside the strictest reading of this tie but inside the searches. The Premier League’s November notice has Manchester United vs Aston Villa on Sunday 8 November at 16:30 GMT, 22:00 IST, on Sky. That is a league game at Old Trafford, five days after Roma. Villa, meanwhile, are at Camp Nou on this same Tuesday. So “Villa and United in November” is two matches: Villa at Barcelona in Europe on the 3rd, United vs Villa in the league on the 8th. If you only remember one, you will brief the wrong competition. Write both down or write neither.",
],
},
"barcelona-vs-aston-villa-ucl-3-nov-2026": {
"excerpt": "Barcelona host Aston Villa on 3 November 2026 in the Champions League at Spotify Camp Nou, 21:00 CET (01:30 IST on 4 Nov). SonyLIV notes.",
"h2": "Camp Nou twice in ten days, two opponents",
"paras": [
"Sunday 25 October is Real Madrid, with the CEST label and the clock-change warning. Tuesday 3 November is Aston Villa, 21:00 CET, cleanly 01:30 IST on the Wednesday. Same stadium name, Spotify Camp Nou, different competition, different crest on the away shirt. If you buy a ticket, read the date on the ticket twice. If you only watch, read the opponent in the SonyLIV title twice. The search engines will offer you the Clásico for weeks after it has been played. This URL is the Villa one.",
"Villa’s earlier European home game is Fenerbahçe on 14 October at Villa Park, 21:00 CEST. Between Villa Park and Camp Nou they have a league month this preview will not fictionalise game by game. The European facts are the ones UEFA and the clubs have printed. Barcelona’s coach, in the club’s own Clásico note, is Hansi Flick. Villa’s coach is not in the schedule line we cited, so the name stays off this page until you check the club. That asymmetry is deliberate.",
"Indian viewers who watched the Clásico after midnight and then have a Wednesday 01:30 start are looking at two late nights in a little over a week, plus whatever league games they follow. Camp Nou on a Tuesday in Europe is a Wednesday shift in India. Say that to anyone you invite. The match is a pleasure only if the person watching does not have to pretend they will sleep.",
"The broadcast bug should say UEFA Champions League, not La Liga. FanCode is the reported India home of the league. SonyLIV is the home of this cup tie. Opening the wrong app is the most common reason a legal subscriber thinks the match is “not on”. It is on. It is on the other service. Check both logos before you conclude the rights have moved.",
"Villa’s league date with Manchester United is a different week. The Premier League lists United vs Aston Villa on Sunday 8 November at 16:30 GMT, which is 22:00 IST, at Old Trafford, on Sky. That is five days after this Camp Nou night. Supporters who follow both clubs will see the same crests twice and should not reuse the Champions League alarm for the league game. Europe is SonyLIV and 01:30 IST. The league is JioHotstar and 22:00 IST. Two subscriptions, two grounds, two competitions. The only shared fact is that both matches are already on a published list, and neither XI is knowable from here.",
],
},
"atletico-vs-bayern-ucl-3-nov-2026": {
"excerpt": "Atlético Madrid host Bayern on 3 November 2026 in the Champions League, 21:00 CET (01:30 IST on 4 Nov) at the Metropolitano. No betting tips.",
"h2": "Which Madrid, which German club",
"paras": [
"“Madrid versus Germany” is not a fixture. Atlético versus Bayern is. Real Madrid versus Leipzig was 21 October. Real Madrid versus Barcelona was 25 October. Bayern versus Dortmund is 31 October. Bayern versus Atlético is 3 November. Four famous games, four pages, four grounds. If a short video uses the Bernabéu tunnel for this tie, it is the wrong tunnel. Atlético’s home is the Metropolitano. The club and UEFA both treat it as such. So does the schema on this article.",
"Bayern’s Saturday before the flight is the Klassiker, 18:30 CET, Allianz Arena. Asking a squad to play Dortmund and then Atlético inside four days is a fair press-conference question and an unfair lineup guess. Wait until Tuesday. Atlético’s October home European date was United on the 13th. The crowd will be compared. The comparison is not a statistic we are willing to invent. Watch the broadcast and decide for yourself whether the ground is up for it.",
"The simultaneous matches are a gift and a problem. United vs Roma and Barcelona vs Villa kick off at the same 21:00 CET. In India that is one 01:30 alarm and three choices. Atlético vs Bayern is the choice if you want the meeting of a Champions League regular from Madrid and the German side who were just at home to Dortmund. It is not a moral duty. It is a preference. State it before kick-off so nobody spends the first half flipping.",
"After the match, the next Madrid European line in this batch’s window is not another Atlético home game. Real’s Matchday 4 game is away to AEK Athens on 4 November, in the earlier band. Different club, next day, different city. Keep the names straight in the group chat and the rest of the week is simple.",
"If you are watching from India on a work night, the Metropolitano’s 01:30 start is the same problem as Old Trafford and Camp Nou, because it is the same whistle. The difference is only which feed you tapped. Set the SonyLIV download or reminder on Tuesday afternoon, charge the phone, and decide in advance that added time belongs to this match and not to a second tab. Bayern’s travel from the Klassiker is the story the pictures will test. You do not need a statistic to see whether the visitors look heavy-legged. You need to be awake for the first twenty minutes, which means going to the app before 01:15, not at 01:29.",
"The Metropolitano’s sponsor styling sometimes appears as Riyadh Air Metropolitano on club and league pages. The ground is the same stadium Atlético used for the United match on 13 October. If a ticket or a broadcast caption uses the longer name, do not go looking for a second venue in Madrid. There is one home ground in this tie. Bayern are the visitors. The whistle, on the lists we used, is 21:00 CET on Tuesday 3 November, 01:30 IST on Wednesday 4 November, and the page should be edited in all three places if UEFA moves it.",
],
},
"slavia-prague-vs-arsenal-ucl-4-nov-2026": {
"excerpt": "Slavia Prague host Arsenal on 4 November 2026 in the Champions League at Fortuna Arena. Working time 21:00 CET (01:30 IST, 5 Nov). Confirm on UEFA.com.",
"h2": "Hold the minute lightly, hold the trip firmly",
"paras": [
"Some facts are solid enough to put in a calendar now: Arsenal are in Prague, the competition is the Champions League, the matchday is the fourth, the ground named on the Bundesliga.com widget is Fortuna Arena, the date is 4 November. The minute is the soft fact. 21:00 CET is the grouping Transfermarkt uses with Leipzig–City and Porto–Napoli. A different widget has shown 20:00. UEFA’s own match page is the one that ends the argument. Until you have seen it, keep two alarms and delete one. 23:15 IST Wednesday if it is the early slot. 01:30 IST Thursday if it is the late slot.",
"Either way, the trip is not Anfield and it is not Munich. Anfield is 1 November, league, 22:00 IST, Sky in Britain, JioHotstar in India. Munich was 21 October, Champions League, 00:30 IST. Prague is the next European away day. Three grounds, three apps if you are in India for the league and Sony for Europe. Write the app next to the alarm. “Arsenal 10pm” is how you open the wrong service.",
"Slavia’s home support will be part of the broadcast story. We can say that without pretending to know the team. Arsenal’s team will be discussed in terms of who played at Anfield three days earlier. That discussion belongs to the Wednesday press conference. Quote it then. A predicted XI published in September will be wrong in detail and confident in tone, which is the worst combination on a match page.",
"If you are editing this article after UEFA confirms the minute, change the FAQ, the bullet list and the schema startDate in one pass. The current schema says Thursday 01:30 IST, matching the 21:00 CET working time. A partial edit is how a rich result shows one hour and the page shows another. Readers forgive a clearly labelled caveat. They do not forgive two confident clocks.",
"Arsenal’s month, written as alarms an Indian supporter can actually keep: 10 October 17:00 IST Leeds at the Emirates, 14 October 00:30 IST Lille, 18 October 21:00 IST Forest, 22 October 00:30 IST Bayern in Munich, 1 November 22:00 IST Anfield, then this Prague night. That is six sittings. Nobody reasonable watches all six to the end. The point of listing them is to stop the Prague page being asked to carry the Anfield kick-off, and to stop the Anfield page being asked to carry Lille. Each URL on this site has one whistle. If you only read one Arsenal guide this autumn, read the one whose opponent is the team you are about to watch, and check the zone letters before you borrow its IST hour for a different week.",
],
},
"fenerbahce-vs-liverpool-ucl-4-nov-2026": {
"excerpt": "Fenerbahçe host Liverpool on 4 November 2026 in the Champions League, 17:45 UTC (23:15 IST) at Şükrü Saracoğlu, Istanbul. Earlier than the 21:00 wave.",
"h2": "Four clocks that all mean the same whistle",
"paras": [
"Istanbul 20:45, central Europe 18:45, Britain 17:45 GMT, India 23:15. All of those are 17:45 UTC on 4 November 2026. If a friend in each city sends a screenshot, the hours will not match and the match will. Reply with UTC if the thread gets stuck. UTC is the one number that does not depend on whose phone is wrong. We have used it in the schema by converting to IST, which is what this site’s readers ask for, and we have spelled the others in the list so nobody has to do the arithmetic on a bus.",
"Liverpool’s previous Sunday is Anfield against Arsenal, 1 November, 16:30 GMT, 22:00 IST. Then this Wednesday. The turnaround is the story the manager will be asked about. The answer is a team sheet you do not have yet. What you can prepare is the app: SonyLIV in India, TNT in Britain, Paramount+ in the US. Log in before 23:00 IST. The early slot is only kind if you are actually in the app when the whistle goes. A late login on a 23:15 kick-off burns the part of the game where away teams either survive the noise or do not.",
"Fenerbahçe’s stadium naming is in a sponsor era. Şükrü Saracoğlu is the historic name readers know. Chobani Stadyumu is a listing name on some live-score pages for the same complex. If you are meeting friends, use the club and the district, Kadıköy, rather than arguing about the sponsor. This is not a travel guide and it is not a ticket office. It is a clock and a competition label: Champions League, Matchday 4, Fenerbahçe at home.",
"Should you stay up for Slavia vs Arsenal afterwards? Only if UEFA has them in the 21:00 CET wave and only if you have the evening for it. Liverpool’s match ending around 01:00 IST and another match starting at 01:30 is a schedule for people who do not have Thursday mornings. Most people should pick Istanbul and watch the Prague highlights later on the same legal app. There is no prize for witnessing both whistles half asleep.",
],
},
"bournemouth-vs-ac-milan-europa-22-oct-2026": {
"excerpt": "Bournemouth host AC Milan in the Europa League on 22 October 2026 at 20:00 BST (00:30 IST, 23 Oct) at the Vitality Stadium. TNT and SonyLIV.",
"h2": "Thursday nights that are not this match",
"paras": [
"15 October is Sturm Graz at the Vitality Stadium, also an 8pm UK kick-off in Sky’s Bournemouth list, Matchday 2. 22 October is Milan, Matchday 3. The grounds match and the visitors do not. A saved search for “Bournemouth Europa” will surface both for a fortnight. Look at the away crest before you tell someone Milan are in Dorset. On the 15th they are not. On the 22nd, if the list holds, they are.",
"Crystal Palace are in the same competition and on the same Thursday they are away at Beşiktaş at 8pm UK, according to Sky’s club-by-club list. Sunderland are earlier, at Lech Poznan at 5:45pm. The English Europa story is a spread of kick-offs, not a single prime-time show. Bournemouth vs Milan is the prime-time one because 20:00 BST is the later band and because Milan are the visitor. That is a description of the schedule, not a ranking of clubs we are inviting you to bet on. There is nothing to bet on this page.",
"Nine days later Milan are at home to Inter. The players who feature on the south coast may or may not feature in the derby. Italian reporters will ask. You can watch both matches, on different apps if the rights split that way: SonyLIV for Europe, and whatever licensed Serie A app is carrying the derby. Do not assume one subscription covers San Siro in the league and the Vitality Stadium in Europe. They are different contracts.",
"Friday 00:30 IST is the same shape as a Champions League Wednesday converted into Thursday. The habit is right. The competition bug must still say Europa League. If the app opens on a Champions League replay, you are one tap from the wrong week. Search the word Milan inside the Europa row. Then leave the phone face down. The match is long enough without a second screen full of rumours.",
"Bournemouth’s league neighbours that fortnight are worth naming so the Europa night is not blamed for a different result. The Premier League moved some Sunday 25 October games because of Europa commitments the Thursday before, including Manchester United vs Bournemouth at 14:00 GMT. So the Milan match on Thursday 22 October is followed by a league trip to Old Trafford on Sunday 25 October. That is a confirmed sequence from the Premier League notice and Sky’s Europa list. It is not a predicted lineup for either game. It does tell you why the squad will look managed. Watch Thursday for what Thursday is: a European home tie under the lights at the Vitality Stadium, kick-off 20:00 BST, 00:30 IST Friday, AC Milan the visitors, Europa League the competition.",
],
},
"india-vs-brazil-3-oct-2026-kolkata": {
"excerpt": "India host Brazil on 3 October 2026 at 7:00 PM IST at Salt Lake Stadium, Kolkata. AIFF confirmed the date. Sony Sports and SonyLIV are the reported broadcasters.",
"h2": "A Saturday in Kolkata, then a normal football week",
"paras": [
"7:00 PM IST on 3 October is early enough that the match should be over before 9:30, added time included, unless the night runs long. That matters because Tuesday is Uruguay at the same ground and the minute for Tuesday is less certain. Do not plan a single trip that assumes both whistles are at 7:00. Plan Saturday firmly. Plan Tuesday once AIFF or the ticket repeats a time. People flying in for “the internationals” need two plans, not one slogan.",
"The squad announcement in early September is a list of players in camp, reported as 26 names under Khalid Jamil. We are not reprinting the list here because camp lists change and a copied list goes stale. The match-day eleven is a different document, published much closer to 7:00 PM. If you are writing a preview for a local page, link the AIFF squad story and say it is a squad. Do not typeset it as a formation.",
"Tickets are the other stale object. Early September reports described a rush on District and lower-priced stands moving quickly. A sentence that says “tickets are available” or “tickets are gone” will be false on a delay of a day. Send people to the official seller and stop. Do not publish a price range from a secondary blog. Prices are an inventory fact, and inventory facts expire.",
"After the final whistle, the football calendar does not pause for India to enjoy it. The Premier League restarts its post-break run on 10 October with Arsenal vs Leeds and United vs Tottenham. The ISL’s reported start is the same 10 October, opener not yet named. Brazil in Kolkata is the international peak of this particular week. It is not the only football that week. Say so, and say it is a friendly. The qualifier talk can wait until the draw that has been reported for December.",
],
},
"india-vs-uruguay-6-oct-2026-kolkata": {
"excerpt": "India host Uruguay on 6 October 2026 at Salt Lake Stadium, Kolkata. AIFF confirmed the date and venue. The kick-off minute is not yet confirmed by the federation.",
"h2": "How to talk about a match when the minute is soft",
"paras": [
"You can still be useful. Tell people the day, the ground, the opponent, the coach’s name as AIFF gave it, the fact that it is a friendly, and the fact that Sony is the reported broadcaster. Tell them not to buy a ticket from a stranger. Tell them Saturday’s Brazil game is not this one. All of that is confirmed or clearly attributed. The only sentence you must hedge is the clock. “Sporting News says 7:00 PM. A database has said 6:30. AIFF has not printed a minute in the announcement we read.” That hedge is the article. Cutting it to make a cleaner headline is how a wrong alarm spreads.",
"Forlán’s Mumbai City season is a nice footnote and a bad thesis. Supporters will enjoy the connection. Analysts should not build a pressing diagram out of a 2016 forward. If he is asked about that year in a Kolkata press conference, the answer belongs in a report of the press conference. Until then, the connection is one sentence, which the AIFF already wrote, and which we have repeated with the date of the note.",
"Travel between the two Kolkata games is the real planning problem. Saturday night ends, Sunday is a gap, Tuesday is Uruguay. Trains and flights that worked for Brazil may be the wrong shape for a Tuesday evening. We have no seat map and no fare. We do have the advice to book the date you can attend and watch the other on SonyLIV. A friendly you see legally from home is a better memory than a ticket you cannot use.",
"Schema on this page currently says 19:00 IST so that a machine has a number matching the most common consumer listing. Humans should read the caveat above the number. If you are a publisher copying our startDate into your own feed, copy the caveat too or do not copy the time. A naked 19:00 in a data file looks more certain than the federation has been. Certainty is the thing we are refusing to fake.",
],
},
"isl-2026-27-season-start-10-october": {
"excerpt": "The ISL 2026-27 season is reported to begin on 10 October 2026 and run to May, with 13 clubs and play-offs. The opening fixture and broadcaster are not yet confirmed.",
"h2": "What a supporter can prepare before the PDF",
"paras": [
"You can learn the 13 names. You can ignore any 14th club until the AIFF adds one. You can expect a home-and-away league and a top-six play-off, because that is what Sportstar reported from the announcement, and you can hold the number 163 lightly in case the fixture PDF counts differently. You can clear the weekend of 10 October as “ISL might start” without clearing a specific hour. You cannot yet print a poster with two crests and a 7:30 PM kick-off. That poster is the thing unofficial calendars are already tempted to draw. Do not be one of them.",
"The national team is the complication next door. Brazil on 3 October and Uruguay on 6 October will use players who have clubs. Whether those players are back for a 10 October league match depends on a fixture list and a release that nobody has published in the sources behind this page. Club sites will start to say “international duty” without saying whether the player misses the opener. Read them as club statements, not as a league schedule.",
"Broadcast uncertainty is commercial, not mystical. A league that has been renegotiating how it is sold will not be helped by fans guessing the app. When the partner is named, the watch page is easy: one logo, one subscription, 163 matches over the months. Until then, the honest watch page is this one. It tells you the season is coming and refuses to send you to a pirate stream “just for the opener”. There is no confirmed opener to pirate. Waiting is free.",
"If you build websites for clubs, and several ISL clubs will be refreshing theirs this month, ship the season page with empty fixture slots rather than scraped guesses. Link the AIFF note, link the Sportstar report, and leave the kick-off field null. That is the same discipline TheTriFusion asks of its own event pages: a startDate that is only a calendar day when the minute is unknown, a location of “India” when the first city is unknown, and a FAQ that says not yet confirmed in plain words. Supporters trust a blank more than they trust a clever fake.",
],
},
}
