def L(*pairs):
    return list(pairs)

POSTS_2 = []

POSTS_2.append(dict(
    id=159,
    slug="leeds-vs-man-united-18-oct-2026-preview",
    title="Leeds vs Man United 18 Oct 2026: IST & TV",
    metaTitle="Leeds vs Man United 18 Oct 2026 — 18:30 IST, Sky | TheTriFusion",
    excerpt="Leeds host Manchester United on 18 Oct 2026 at 14:00 BST (18:30 IST) at Elland Road. Sky Sports in the UK, India watch notes.",
    og1="Leeds vs Man United:",
    og2="18 Oct — 18:30 IST",
    hue=24,
    layout="ground",
    tags=["leeds vs man united", "premier league", "elland road", "18 october 2026", "football"],
    opener="Elland Road on a Sunday early kick-off is one of the fixtures Sky Sports put on its October billboard, and the clock is earlier than Indian fans expect from a United away day. Leeds United host Manchester United on 18 October 2026 at 14:00 BST, which is 18:30 IST and 9:00am EDT. It shares the afternoon with Nottingham Forest vs Arsenal at 16:30 BST, so a single “Sunday football” alarm will catch only one of them. This page is the Leeds version: ground, broadcaster, and the matches it is not.",
    verify="The Premier League’s October amendment notice and Sky Sports’ published October–November list both place Leeds vs Man Utd at 14:00 on Sunday 18 October, live on Sky Sports. Radio Times lists the same 2pm Sky selection. The ground is Elland Road, Leeds. India rights for 2026/27 are Star Sports and JioHotstar, as Sporting News reports. Confirm the EPG the day before.",
    time_h2="Kick-off converted to IST",
    rows=L(
        ("Date", "Sunday, 18 October 2026"),
        ("Kick-off UK", "14:00 BST"),
        ("Kick-off India", "18:30 IST"),
        ("Kick-off US East", "9:00am EDT"),
        ("Venue", "Elland Road, Leeds"),
        ("Competition", "Premier League 2026/27"),
        ("UK selection", "Sky Sports"),
    ),
    time_note="18 October is still British Summer Time. The change to GMT happens a week later, in the early hours of 25 October. 14:00 BST plus 4 hours 30 minutes is 18:30 IST. Do not apply the winter +5:30 conversion or you will arrive an hour late.",
    watch_h2="Where the match is shown",
    india="JioStar’s Premier League package in India is Star Sports on television and JioHotstar on streaming. A Sunday 18:30 IST kick-off sits in early evening, which is a comfortable window, but the app tile is the authority for which Star channel carries the Leeds game rather than the Forest game that follows. Search the fixture name.",
    uk="Sky Sports selected this match. Sky’s own write-up groups it with Forest vs Arsenal as part of the 18 October live set, and Radio Times currently files the 2pm kick-off as Sky Sports with the channel label still marked TBC on that line. Check the Sky guide on Saturday night for Main Event versus Premier League.",
    us="US viewers should use the NBC / Peacock weekly listing. 9:00am EDT is a morning window. We will not invent a network bug for a match whose US assignment is published week by week.",
    safety="Stick to Sky, Peacock, Star Sports or JioHotstar. A free stream with a countdown clock is not a broadcaster.",
    sections=[
        ("Elland Road, not Old Trafford", [
            "Manchester United’s home match against Tottenham is the Saturday before the international window closes into league football, 10 October at Old Trafford, 17:30 BST. This Leeds game is eight days later and it is an away trip. United also host Bournemouth on Sunday 25 October at 14:00 GMT, by then on winter time, which Sky has also selected. Three United league matches in a fortnight means three venues. Elland Road is the Leeds one. If a preview says Old Trafford on 18 October, it is describing a different week.",
            "Leeds’ own previous Saturday, 10 October, is the trip to Arsenal at the Emirates at 12:30 BST, on TNT Sports rather than Sky. Supporters who only follow Leeds should keep both: north London at lunchtime on the 10th, then home to United at 14:00 on the 18th. The city of Leeds is in West Yorkshire. We are not publishing ticket prices or claiming a spare seat. The club site is the source for entry rules.",
        ]),
        ("What the double Sunday actually is", [
            "Sky’s 18 October block is not a single match. The Premier League notice lists Bournemouth vs Sunderland and Brighton vs Crystal Palace at 14:00 as well, moved because of Europa League fixtures the Thursday before, plus Leeds vs Man Utd at 14:00 and Nottingham Forest vs Arsenal at 16:30. In India that is 18:30 IST for the early games and 21:00 IST for Forest vs Arsenal. You can watch Leeds–United and still see the Arsenal kick-off if you plan a break between them. You cannot treat them as one broadcast.",
            "Team news is not yet confirmed for either side. United’s European week includes the trip to Atlético Madrid on 13 October, already covered on this site, and a home Champions League night against Roma is not until 3 November. Leeds are not in that Champions League list. Rotation talk should wait for the managers’ Friday or Saturday comments. We will not name a starting XI or a score.",
        ]),
        ("A note on rivalry language", [
            "Leeds against Manchester United carries a long league history, and Sky’s preview called the October trip a meeting with rivals. That is enough context. We are not attaching a head-to-head count, a last-meeting score, or a table position, because those numbers change and invented ones travel. On the morning of 18 October, premierleague.com has the only table worth quoting.",
            "For anyone publishing a local page, write “Sunday 18 October, 14:00 BST / 18:30 IST, Elland Road, Sky Sports” in the first sentence. The SportsEvent startDate on this page is 2026-10-18T18:30:00+05:30. If Sky moves the kick-off, that timestamp has to move with the sentence. Calendar products that TheTriFusion builds for media teams keep those two fields in one edit so search results do not show a stale IST clock.",
        ]),
    ],
    expect_h2="Neutral watch points",
    expect=[
        "How Leeds start at home against a side that has already played a European away week.",
        "Wide areas: Elland Road games often swing on the first full-back who gets isolated.",
        "Set-piece delivery, without turning that into a prediction.",
        "Whether the 14:00 start shows in the first ten minutes of sharpness.",
        "The official sheets, posted close to kick-off, rather than a leaked graphic.",
    ],
    expect_note="This is not a tips page. No odds are listed.",
    checks=[
        "Alarm at 18:15 IST.",
        "Use the BST conversion, not GMT.",
        "Keep Forest vs Arsenal as a second event at 21:00 IST.",
        "Confirm the Sky channel label on Sunday morning.",
        "Skip any XI that is not on the club site.",
    ],
    live_links=L(
        ("/blog/man-united-vs-tottenham-10-oct-2026-preview", "United vs Tottenham on 10 October"),
        ("/blog/atletico-vs-man-united-ucl-13-oct-2026", "Atletico vs Man United in Europe"),
        ("/blog/liverpool-vs-man-city-11-oct-2026-preview", "Liverpool vs Man City the week before"),
    ),
    sib_sentence='Arsenal’s lunchtime match with Leeds on 10 October is in <a href="/blog/arsenal-vs-leeds-10-oct-2026-preview">a separate preview</a>, and Forest vs Arsenal later the same Sunday is <a href="/blog/nottingham-forest-vs-arsenal-18-oct-2026">here</a>.',
    hub="/services/digital-marketing",
    hub_label="digital marketing services",
    faqs=L(
        ("What time is Leeds vs Manchester United in IST?", "18:30 IST on Sunday 18 October 2026."),
        ("What is the UK kick-off?", "14:00 BST at Elland Road."),
        ("Is it on Sky or TNT?", "Sky Sports selected it. TNT’s Saturday lunchtime game that month is a different fixture."),
        ("Where in India?", "Star Sports and JioHotstar. Confirm the tile on the day."),
        ("Is Old Trafford the venue?", "No. Leeds are at home at Elland Road."),
        ("Are lineups in this guide?", "No. They are not yet confirmed."),
    ),
    close="Put 18:30 IST in the calendar as Elland Road, then leave room for the 21:00 IST Forest–Arsenal kick-off if you are watching both.",
    event=dict(
        type="SportsEvent",
        name="Leeds United vs Manchester United",
        startDate="2026-10-18T18:30:00+05:30",
        organizer="Premier League",
        location=dict(name="Elland Road", addressLocality="Leeds", addressCountry="GB"),
    ),
))

POSTS_2.append(dict(
    id=160,
    slug="nottingham-forest-vs-arsenal-18-oct-2026",
    title="Forest vs Arsenal 18 Oct 2026: Time IST & TV",
    metaTitle="Forest vs Arsenal 18 Oct 2026 — 21:00 IST, Sky Sports | TheTriFusion",
    excerpt="Nottingham Forest host Arsenal on 18 Oct 2026 at 16:30 BST (21:00 IST) at the City Ground. Sky Sports UK, India watch notes.",
    og1="Forest vs Arsenal:",
    og2="18 Oct — 21:00 IST",
    hue=140,
    layout="story",
    tags=["nottingham forest vs arsenal", "premier league", "city ground", "18 october 2026", "football"],
    opener="The City Ground under floodlights is the later of Sky’s two headline selections on Sunday 18 October 2026. Nottingham Forest host Arsenal at 16:30 BST, which is 21:00 IST and 11:30am EDT. Sky’s own October piece singled out Mikel Arteta’s side travelling to Forest as one of the matches it would show live, alongside Liverpool’s dates with Manchester City and Arsenal. The early game that day is Leeds vs Manchester United at 14:00 BST. They are neighbours on the schedule, not the same broadcast.",
    verify="Premier League matchweek amendments list Sunday 18 October, 16:30, Nott'm Forest v Arsenal (Sky Sports). Sky Sports and Radio Times both carry the 4:30pm kick-off on Sky Sports Main Event, Premier League and Ultra HD in the Radio Times grid. Venue is the City Ground, Nottingham, Forest’s home. India: Star Sports and JioHotstar. Confirm the EPG.",
    time_h2="IST, UK and US clocks",
    rows=L(
        ("Date", "Sunday, 18 October 2026"),
        ("Kick-off UK", "16:30 BST"),
        ("Kick-off India", "21:00 IST"),
        ("Kick-off US East", "11:30am EDT"),
        ("Venue", "City Ground, Nottingham"),
        ("UK selection", "Sky Sports"),
        ("Same-day early game", "Leeds vs Man United, 14:00 BST / 18:30 IST"),
    ),
    time_note="Still BST on 18 October. 16:30 plus 4 hours 30 minutes is 21:00 IST. The GMT switch is Sunday 25 October. Using a winter offset on this date makes the match look an hour later than it is.",
    watch_h2="Broadcast path",
    india="The 21:00 IST slot is the familiar Super Sunday hour for Indian Premier League viewers. Star Sports and JioHotstar hold the 2026/27 rights. Because Leeds vs United kicks off at 18:30 IST on the same rights package, the stream may hand from one match to the next. Open Forest vs Arsenal as its own event so the app does not leave you on a post-match studio.",
    uk="Sky Sports is the selector. Radio Times names Sky Sports Main Event, Sky Sports Premier League and Sky Sports Ultra HD for the 4:30pm Forest game. That is a different package from TNT’s Saturday lunchtime games. A Sky subscription is the UK route; TNT is not.",
    us="11:30am EDT fits a late-morning US window on NBC platforms or Peacock. The weekly grid, not this page, assigns the specific channel. Check it on Saturday.",
    safety="Licensed apps only. If a link asks you to install a new player, close it.",
    sections=[
        ("Where Forest vs Arsenal sits in Arsenal’s month", [
            "Arsenal walk into the City Ground eight days after hosting Leeds at the Emirates on 10 October at 12:30 BST, and five days after hosting Lille in the Champions League on 13 October. The Munich trip to Bayern is on Wednesday 21 October, three days after Forest. That is three competitions in eleven days. Whatever the team sheet is at the City Ground, it will be discussed against that stack. The sheet itself is not yet confirmed, and this guide will not invent one.",
            "Forest’s home ground is the City Ground, on the banks of the Trent in Nottingham. It is not the Emirates and it is not Elland Road, even though all three grounds host a televised game across these two October weekends. Away fans and travelling supporters should use the club’s entry instructions. We have no ticket inventory and we are not quoting a price.",
        ]),
        ("The Sunday sequence, written as a plan", [
            "A practical Indian evening looks like this. 18:15 IST, confirm the Sky or JioHotstar tile for Leeds vs Manchester United. Watch or follow until full time. Reset before 20:45 IST for team news from Nottingham. Forest vs Arsenal starts at 21:00 IST. In the UK that reset is the gap between 14:00 and 16:30 BST. In the US it is the gap between 9:00am and 11:30am EDT. One sofa, two kick-offs, two team sheets.",
            "Sky’s article also flags Liverpool vs Arsenal on 1 November as the next Arsenal Super Sunday. That match is at Anfield at 16:30 GMT, which is 22:00 IST, and the timezone label changes because the UK has moved to GMT by then. Do not copy the 21:00 IST habit from this Forest game onto the Anfield game. The UK hour looks similar. The Indian hour is not.",
        ]),
        ("What we will and will not say about the match", [
            "We will not publish a league table, a betting line, or a score forecast. Forest against Arsenal has years of Premier League meetings behind it, some tight, some not. The only table that matters on 18 October is the live one. Check it on the Premier League site that morning and ignore a graphic that does not show its date.",
            "Neutral things worth a second look once the match is on: whether Arsenal’s midweek European minutes show after an hour, how Forest use the City Ground crowd on the first attacking set piece, and which wide player is asked to pin Arsenal’s full-back. Those are watch-points for a viewer, not a coupon. If you are building a match centre for a publisher, keep the FAQ answers in the same words as the visible clock so the schema and the page do not disagree.",
        ]),
    ],
    expect_h2="On the pitch, once the sheet is real",
    expect=[
        "Arsenal’s turnaround from Lille on 13 October to Nottingham on 18 October.",
        "Forest’s first phase of pressure at home.",
        "Set pieces at the Trent End side of the ground, described by the pictures, not by a guess.",
        "Substitutions after 60 minutes given the Bayern trip on 21 October.",
        "Anything in the referee’s appointment only after the league publishes it. It is not yet confirmed here.",
    ],
    expect_note="No odds, no correct-score claim, no injury rumour presented as fact.",
    checks=[
        "21:00 IST alarm, separate from the 18:30 IST Leeds game.",
        "Sky in the UK, JioHotstar or Star Sports in India.",
        "Do not reuse this IST conversion after 25 October.",
        "Wait for club team news.",
        "Read the Anfield date as GMT when you get to 1 November.",
    ],
    live_links=L(
        ("/blog/arsenal-vs-lille-ucl-13-oct-2026", "Arsenal vs Lille on 13 October"),
        ("/blog/bayern-vs-arsenal-ucl-21-oct-2026", "Bayern vs Arsenal on 21 October"),
        ("/blog/liverpool-vs-man-city-11-oct-2026-preview", "Liverpool vs Man City context"),
    ),
    sib_sentence='See also <a href="/blog/leeds-vs-man-united-18-oct-2026-preview">Leeds vs Man United earlier the same Sunday</a> and <a href="/blog/liverpool-vs-arsenal-1-nov-2026-preview">Liverpool vs Arsenal on 1 November</a>.',
    hub="/ecommerce-development",
    hub_label="ecommerce development",
    faqs=L(
        ("What time is Nottingham Forest vs Arsenal in IST?", "21:00 IST on Sunday 18 October 2026."),
        ("What time is kick-off at the City Ground?", "16:30 BST."),
        ("Who shows it in the UK?", "Sky Sports. Radio Times lists Main Event, Premier League and Ultra HD."),
        ("Who shows it in India?", "Star Sports and JioHotstar. Confirm the app tile."),
        ("Is this the Leeds match?", "No. Leeds vs Manchester United is 14:00 BST the same day."),
        ("Is the referee named here?", "Not yet confirmed on this page."),
    ),
    close="Treat 21:00 IST as the Forest kick-off only. The Anfield meeting two weeks later needs its own GMT conversion.",
    event=dict(
        type="SportsEvent",
        name="Nottingham Forest vs Arsenal",
        startDate="2026-10-18T21:00:00+05:30",
        organizer="Premier League",
        location=dict(name="City Ground", addressLocality="Nottingham", addressCountry="GB"),
    ),
))
