"""Unique expansions so every Batch B post clears 1,400 words."""

EXTRAS = {}

EXTRAS[181] = '''
<h2>Indore on a Sunday that already has a race and a marathon</h2>
<p>11 October 2026 is a stacked sports Sunday, which is why the Indore T20I needs its own sentence in any diary. The Singapore Grand Prix race is at 5:30 PM IST. The Chicago Marathon’s first wave is at 6:00 PM IST. This cricket match is at 7:00 PM IST. A household that follows all three will see the race start, the marathon waves go off during the race’s later laps, and the cricket toss around the time the marathon’s last wave is moving. None of those clocks is a substitute for the others. If you are the person who sends the family WhatsApp, send three lines, not one “evening sports” line.</p>
<p>Holkar Stadium’s match-day operations are a Madhya Pradesh Cricket Association matter. Gate opening, parking and the bag policy are not in the BCCI season table. Look them up on the association channel the day before if you are going. Supporters coming from Bhopal or from the airport should add time for Sunday traffic rather than assuming a 6:40 PM arrival still catches the anthem. The broadcast, if you are not in the ground, is the JioStar path described above. A full house does not change the 7:00 PM start.</p>
<p>Editors who update this page after Ranchi should add one sentence with the series score and nothing else at the top. Do not rewrite the venue paragraph to include a “momentum” claim you cannot source. A two-day gap is short for bowlers and long enough for a selection change. Both can be true, and only the sheet will show which one the team chose. Keep the canonical URL stable so the Sunday-morning searcher lands on Indore and not on the series hub’s first paragraph about Lucknow.</p>
'''

EXTRAS[182] = '''
<h2>A Wednesday night at Uppal, after a Sunday in Indore</h2>
<p>The turnaround from Indore on Sunday to Hyderabad on Wednesday is the tightest travel of the T20I leg for anyone following the team in person, and it is still a normal gap for the squads, who move on charter schedules the boards arrange. Spectators do not. If you hold a ticket only for Hyderabad, do not build a plan that depends on the Indore result for whether you attend. The match is on the calendar either way. What changes is the meaning of the result, not the existence of the fixture.</p>
<p>Rajiv Gandhi International Stadium is in Uppal, east of central Hyderabad. Evening traffic on a Wednesday can make a 6:15 PM departure from HITEC City late for a 7:00 PM start. The association’s gate list is the map that matches your stand. Food and water rules follow the venue’s current security circular, which this preview will not invent. Families with children often leave at the innings break if the next morning is a school day. That is a practical choice, not a comment on the match.</p>
<p>For a newsroom, the responsible Wednesday workflow is: pull the official series score at noon, confirm the JioHotstar tile shows Hyderabad, and only then write a stakes paragraph. If the series is over, say so in the first line and still give the start time, because people watch dead rubbers. If it is alive, say what a win does and stop before you predict it. The Bengaluru match on Saturday remains scheduled regardless. Do not announce a cancellation that the BCCI has not announced.</p>
<p>Hyderabad’s night cricket also draws a large television audience outside the stadium, which is why the 7:00 PM IST line has to be boringly exact. A graphic that says 7:30 because a producer remembers an IPL slot will desync every alarm in the country. The BCCI row for this tour’s T20Is is 7:00 PM, five times, including this Wednesday. Repeat that, and name the city in the same sentence so the graphic cannot be reused for Bengaluru by mistake.</p>
'''

EXTRAS[183] = '''
<h2>Bengaluru as a Saturday night, not automatically a final</h2>
<p>Chinnaswamy, if the match page confirms that ground, sits inside a dense part of the city. A 7:00 PM international on a Saturday means Cubbon Park-side traffic and metro crowds that have nothing to do with cricket until the last hour, when they have everything to do with it. Leave earlier than the start time suggests. The KSCA’s match-day note is the one that names which gate uses which QR. A ticket bought from an unofficial reseller is a common way to stand outside a full ground. This page cannot check a QR for you.</p>
<p>The broadcast window is friendly for India and awkward for the UK, where 2:30 PM on a Saturday competes with other sport. That competition does not move the cricket. If you are clipping the last over for a Monday newsletter, label it as the fifth T20I in Bengaluru and include the series score from the official card. A six without the scoreline is how a dead rubber gets described as a title-clincher. The presentation ceremony, if the boards hold one because the series has just been decided or because it is the end of the tour, is an official event. Do not announce a trophy lift that is not on the board’s run of show.</p>
<p>After this match the men’s international home list goes quiet until Sri Lanka in December. Domestic cricket does not go quiet: the Ranji Trophy’s first phase is already inside its 11 October to 5 November window by the time Bengaluru is played. A sports desk that only staffs internationals will miss the first-class round happening the same week. Different competitions, different pages, same newsroom.</p>
<p>Saturday crowds at an India T20I also mean the highlight clips travel faster than the score. If you republish a clip, keep the city and the match number in the caption so a Ranchi six from the previous Friday does not get re-labelled as the Bengaluru finish. The licensed broadcaster’s clip is the one you can use if your rights allow it. A screen recording of the TV is not a substitute, and it is a good way to get a post taken down on the morning after the series ends.</p>
'''

EXTRAS[184] = '''
<h2>Raipur on the Friday before the men’s finale</h2>
<p>16 October is the evening before the men’s fifth T20I in Bengaluru. The women’s game is at the same 7:00 PM IST hour, one night earlier, in a different state. A channel that cuts from one to the other needs a lower-third that says Women, Raipur, Zimbabwe, first T20I. Without those four words, the highlights will be filed under the men’s tour by every editor working from a phone. The ICC’s “first bilateral” line belongs in the copy. It is the reason a viewer who does not follow women’s cricket might still stop scrolling, and it is a fact from the ICC note rather than a marketing adjective.</p>
<p>Shaheed Veer Narayan Singh International Stadium, if that is the ground the match page confirms, is in Naya Raipur, not in the oldest part of the city. Friday traffic and the distance from the railway station catch people who searched only “Raipur stadium” and followed a pin for a different ground. Use the board’s map. The three T20Is are on consecutive odd dates: Friday, Sunday, Tuesday, all 7:00 PM. A supporter can stay for the set. An ODI ticket for Baroda the next Friday is a different purchase in a different state.</p>
<p>Squad announcement timing is the other trap. Boards often name a squad several days out and a playing eleven on the morning of the game or at the toss. Quote the document you actually have. If you only have a squad of fifteen, do not publish an eleven. Championship points are not the story of this T20I; they are the story of the Baroda ODIs. Mixing the two is how a T20 result gets entered on a championship table where it does not belong.</p>
<p>Women’s matches on a Friday night also compete with whatever else is on Star Sports. Open the guide and read the title, not just the time. A 7:00 PM tile that says West Indies is the men’s series, which is in Bengaluru the following evening, not this one. If both are listed, watch the one you meant. Families in Raipur who are at the ground do not need the stream; everyone else does, and the wrong tile is the most common complaint on nights when two India teams play on back-to-back days.</p>
'''

EXTRAS[185] = '''
<h2>Baroda on a Friday afternoon, with a championship table attached</h2>
<p>23 October is also the Friday before several other global sports nights, but the ODI does not wait for them. A 2:00 PM start in Vadodara means the toss is a lunchtime item in India and a breakfast item in the UK. Newsdesks that staff cricket only in the evening will miss the first innings entirely. If you are rostering a live blog, the shift starts before 1:30 PM IST, not at 7:00 PM. The Raipur habit will make you late.</p>
<p>Kotambi, the ground named in several roundups of this series, is on the edge of Vadodara. Day-night or afternoon heat is a ground question the association can answer in its match note; the BCCI row only gives 2:00 PM. Spectators should carry the ticket name that matches the board, whether it says Baroda or Vadodara, and should not assume a city-centre hotel is a short walk. The second and third ODIs are Sunday and Wednesday, same start, same city. Hotel plans that cover only Friday will strand you if you meant to see the championship series rather than one game.</p>
<p>When you write the points update, wait for the ICC’s championship page. A bilateral win is not always the same number of points as a win with a bonus, and a washout has its own line in the playing conditions. If you do not have that document open, write “see the ICC table” and do not invent a points swing. That single habit is the difference between a useful championship recap and a wrong one that ranks because the match was searched.</p>
'''

EXTRAS[186] = '''
<h2>How to sit with an unpublished toss time</h2>
<p>A fixture without a clock is still publishable if you say the clock is missing. The failure mode is the opposite: a site picks 2:30 PM IST because three score widgets agree, then the PCB posts 3:00 PM local and every copied calendar is half an hour off in India and an hour off somewhere else. Pakistan Standard Time is UTC+5. IST is thirty minutes ahead of it, all year. When the PCB time arrives, the conversion is mechanical. Until it arrives, leave the field blank in your CMS and visible as “not yet confirmed” in the article. Searchers prefer a blank to a confident error, and so do the people who set alarms.</p>
<p>The tri-series also asks for a table module, not a single-match headline. England play Pakistan twice and Sri Lanka twice before a final they might not reach. A page titled as if 20 October were the final will need a correction that loses the snippet. Link the Lahore date, 25 October, in the same module, and remember that 25 October is the day the UK leaves British Summer Time. The Rawalpindi game is not on that knife-edge. The Lahore game is. Build the second match’s timezone from scratch when you write it, rather than copying this page’s UK offset.</p>
'''

EXTRAS[187] = '''
<h2>What a domestic round looks like once the PDF exists</h2>
<p>When the BCCI or a state association publishes round one, the useful update is a table: match number, home side, away side, ground, start time, and the dates of the three or four playing days. Do not collapse a multi-day game into a single evening. Readers who only know T20s will ask who won on 11 October. The honest answer, for a first-class match that started that morning, is often “no one yet; it is lunch on day one” or “the game is scheduled across several days”. Say that. A Ranji result is an outright result or a first-innings lead at the end of the match, and those phrases should be used exactly, because they mean different things on the points table.</p>
<p>Coverage volume will be uneven. A game between two Elite contenders may have a stream. A Plate game may have a scorer and a phone. Both are the competition. If you are a supporter of a smaller association, the official scorecard is the product you should bookmark, and the JioHotstar domestic rail is the place to check whether video exists that morning. Do not pay a random channel that promises a “live Ranji feed” outside the rights holder. The 2023–2028 domestic listing points at JioStar. Anything else needs a second source.</p>
'''

EXTRAS[188] = '''
<h2>A sprint Saturday before a race Sunday</h2>
<p>Singapore’s Saturday is two appointments, not one. The sprint at 2:30 PM IST is a full race with points under the sprint rules, short enough that a viewer can watch it and still have an afternoon. Qualifying at 6:30 PM IST is the session that sets Sunday’s grid, and it is easy to miss if you only put “race” in the calendar. Set both. If you are in India and you also want the Indore T20I at 7:00 PM on Sunday, the race at 5:30 PM is the conflict, not the sprint. Saturday is the cleaner Formula 1 day for a cricket household. Sunday is the compromise.</p>
<p>Street-circuit weekends also punish late arrivals at the track. The sporting timetable is not the gate-opening timetable. Spectators should read the circuit’s access note for 2026 rather than a 2024 blog’s recommended train. The FIA start time does not move because a train is late. On television, the world feed’s opening shot is usually the paddock in daylight fading into floodlights. That visual is how you know you are on the right session. If the cars are in daylight and the graphic says Sunday race, you are on a replay or on the wrong sport.</p>
<p>Humidity is the other thing the commentary will mention all evening. It is a real condition of a night race on a street by the water, and it shows up as driver cooling and as mistakes, not as a number this preview should invent. You do not need a track-temperature graphic from a previous year. Watch the visors and the pit-wall radio captions if the world feed shows them. The race start remains 5:30 PM IST even if the formation lap feels longer than you expected.</p>
'''

EXTRAS[189] = '''
<h2>Staying up, or choosing the replay on purpose</h2>
<p>1:30 AM IST is a choice. Some viewers will make it for qualifying at 2:30 AM the night before and then regret a Monday race start as well. A practical plan is to treat qualifying as the live session if you can only lose one night’s sleep, and to watch the race as a licensed replay on Monday evening if FanCode offers one. Say “replay” if it is a replay. Publishing a Monday-evening recap that uses the present tense is how readers think the race has not started. The classification can also change after the flag if stewards apply a penalty. A recap written at 3:00 AM IST should say the result is provisional until the stewards’ window closes, which the FIA documents describe and which the broadcast usually captions.</p>
<p>Altitude is the condition you can mention without a prediction. Teams talk about cooling, about wing levels and about the long run to the stadium section. You will hear those words in the commentary if you are awake. You do not need to add a tyre-strategy graphic you copied from 2024. The 2026 cars are a new generation. If a technical claim is not in that weekend’s official preview, it does not belong in the article. The same restraint applies to weather. Mexico City in early November can be cool in the morning and mild in the afternoon. The race is a 2:00 PM local start. Look at a forecast on Friday, not at a September average.</p>
'''

EXTRAS[190] = '''
<h2>Evening in India, afternoon at Interlagos</h2>
<p>10:30 PM IST is late but it is not Mexico’s 1:30 AM. A household can watch the start and still sleep at a normal hour if the race is a routine length. It often is not, because Interlagos produces safety cars, and a safety car stretches a broadcast without moving the scheduled start. Plan the start, not a guessed finish. Qualifying at 11:30 PM IST on Saturday is the harder alarm. People who skip qualifying and only watch the race still need the grid, which the official classification publishes on Saturday night. Read that, rather than a screenshot that omits a penalty.</p>
<p>Rain is the other Interlagos habit. It is not a promise for 8 November. If the sky on the world feed is dark at a 2:00 PM local start, the session can become a wet-weather race in minutes. The start time does not change because the radar is red; a delay, if there is one, is a race-control message. Quote that message if you are live-blogging, and do not invent a new start from a weather app. The India viewer’s job at 10:30 PM is simpler: be on FanCode, or on whichever legal tile is actually showing Sao Paulo, and ignore a stream that asks you to install a new player.</p>
<p>São Paulo the city is also in the news for reasons that are not this race. Election coverage from October uses the same country name and a different date. Keep the Grand Prix URL specific to 8 November and to Interlagos so a reader looking for a polling station does not land on a lap chart. The circuit’s full name, Autódromo José Carlos Pace, belongs in the first screen alongside the nickname. People search both, and only one of them is on the gate.</p>
'''

EXTRAS[191] = '''
<h2>Using the China offset without inventing a session</h2>
<p>Masters 1000 days have a shape even before the clock is published. Qualifying and early rounds sprawl across outer courts. The second week compresses onto Centre Court, with a day session and sometimes a night session. Shanghai has used night sessions in recent editions; whether 2026 does is a timetable question for the tournament, not a fact to copy from memory. When the order of play appears, it will be in China Standard Time. Subtract two hours and thirty minutes, and write both times in the same row so a reader in Mumbai does not do the arithmetic wrong under pressure. If the line says “not before 7:00 PM”, the IST line says “not before 4:30 PM”, and you keep the words “not before”. Dropping them is how a delayed match looks like a published error.</p>
<p>Travelers should buy from the official ticket channel named on the ATP page and should check visa rules for China separately. This guide is not a visa page and not a price list. Players’ practice schedules are not public in a reliable way a week out. Showing up at the gate for a practice because a fan account named an hour is a good way to see an empty court. The match you have a ticket for is the one on the ticket.</p>
<p>Shanghai’s place on the calendar, between the early Asian swing and the flight to Europe, is why withdrawals cluster here. A withdrawal is a statement from the player or the tournament. A “likely to skip” post is not a withdrawal. If you maintain this page through the fortnight, add results only from the ATP draw, one round at a time, and leave the 7 October start date in the introduction so late searchers can still see when the event began. The Paris Masters is the next Masters, not a continuation of this draw.</p>
'''

EXTRAS[192] = '''
<h2>Indoor fortnight, standard time, Nanterre not central Paris</h2>
<p>Nanterre is on the western side of the Paris agglomeration, at La Défense, not a walk from a hotel in the Marais. The address on the venue note — 99 jardins de l’Arche — is the one to put in a map. Spectators who search only “Paris Masters stadium” sometimes land on an older venue the tournament has left. The 2025 edition was the first at La Plénitude Arena, according to the venue’s own recap, and 2026 is the return. Transport notes from the arena, when they are published for ticket holders, beat a blog’s suggestion of a particular RER stop. Arrive for the session on your ticket, not for a fictional all-day ground pass, unless your ticket says that.</p>
<p>Because the whole event sits after the European clock change, every published Paris time converts to IST by adding four hours and thirty minutes. A night session that starts at 8:00 PM in Nanterre, if that is what the order of play eventually says, is 12:30 AM IST the next day. That is the Mexico-Grand-Prix problem in miniature: the date in the headline and the date in India may differ for a single session. Write both dates when you update this page. Early-round afternoon sessions will stay on the same Indian date. Do not use one conversion for the whole fortnight.</p>
<p>The draw will not be complete on 31 October if qualifying is still being played. A “round of 16 preview” published on the Saturday the event starts is early. Wait until the round actually exists. Seeds are a list, not a prediction of who reaches Sunday the 8th.</p>
<p>Indoor tennis also changes how a viewer in India should plan the night. There is no rain delay to blame if you miss the start, only the clock. Once the order of play is out, put the Centre Court session into a phone alarm with the IST date written in words, because a 12:30 AM start belongs to the next morning even when Paris still says Sunday night. Doubles sessions are shorter and often earlier. If the person you are following is a doubles player, do not wait for the singles night session and then complain the match already finished. The ATP live centre separates the draws. Use the right one, and keep betting graphics off any screenshot you repost.</p>
<p>Nanterre’s arena is large enough that a first-week ticket can be a long way from the court and still be a real ticket. That is a seating fact, not a complaint to invent about prices. Session lengths indoors are more predictable than outdoor Masters weeks, which is the practical advantage for an India viewer setting an alarm. Use it. When the quarter-finals arrive, the schedule tightens and the “not before” windows get shorter. Until that round exists, do not publish a quarter-final time.</p>
'''

EXTRAS[193] = '''
<h2>A finals week, not an eight-name poster</h2>
<p>The WTA Finals reward a specific kind of page: dates, place, surface, and a refusal to counterfeit the field. By early November the race is usually clear enough to name the qualifiers, and those names should be copied from the WTA race page with the date you checked. In late September they should not be copied from anywhere. Group draws, once released, tell you who plays whom on the opening days. A player can be in the field and not play on 8 November. The order of play decides that. Pacific Standard Time, after the US clock change on 1 November, is the zone to convert. Adding thirteen hours and thirty minutes to a local afternoon often lands you on an Indian morning the next day. Put the Indian date in the sentence, not just the hour.</p>
<p>Doubles is easy to omit and easy to get wrong. The doubles field is smaller and the session is often earlier or later than the singles match a casual viewer came for. If your watch guide only lists the singles, say so. Indian Wells in November is also not the March 1000. Hotels and ticket inventory are different events. Search the Finals, not “Indian Wells tennis”, or you will buy a date in the wrong season. The WTA’s own page is the disambiguator because it prints November.</p>
<p>A practical India plan, once the order of play exists, is to pick one session a day rather than trying to stay up for every group match. Group play spreads across several days, and a player you follow might appear in the afternoon Pacific time, which is the middle of the Indian night, or in the evening Pacific time, which is the next Indian morning. Write the session down with the Indian date. If you only want the final, that is the last weekend of the 8–15 November window, and the exact day inside that weekend is an order-of-play fact, not something to assume is Sunday night. Hard courts are the WTA’s label for the event. Do not describe the surface as clay because a different Indian Wells memory got in the way.</p>
<p>The ATP Finals in Turin are a different tour, a different city and a later date. They are not a second week of this event. If a search result mixes the two, check the organiser. WTA means the women’s finals in Indian Wells on these dates. ATP means the men’s finals, which this batch does not cover because they sit further out. Keeping the names apart is the whole job of the headline.</p>
'''

EXTRAS[194] = '''
<h2>Afternoon in Detroit, after midnight in India</h2>
<p>A 3:00 PM Eastern tip is a local convenience and an Indian inconvenience. If you are watching from India, the honest choice is often the replay or the box score at breakfast, unless this specific Pistons-Celtics pairing is the one you care about. The Knicks banner at 4:30 AM IST is the game more people will clip. Knowing that helps you set expectations: social feeds on Wednesday morning in India will be full of Madison Square Garden, not Little Caesars Arena. The first game of the season can be overshadowed and still be the first game. Cite the 12:30 AM start if you are writing a “season is open” post, then mention the banner as later context.</p>
<p>Roster notes from NBA.com are a snapshot from the schedule release, not a starting five. Between August, when the league described the off-season moves, and 20 October, further signings and injuries can change who is available. The only lineup worth posting is the one the team or the league posts on game day. Until then, describe the matchup as Boston at Detroit, opening tip, NBC, and leave the names of the five blank. That is less exciting and it stays true.</p>
<p>If you are building a watch party in India, the 12:30 AM start is the door time, not 3:00 AM and not 3:00 PM. Tell people the date is Wednesday. A Tuesday-night invitation will gather a room for a game that is already in the second quarter or already over, depending on how wrong the conversion was. Peacock is a US product. An Indian viewer who downloads it may find the game geo-blocked, which is the rights system working. That is another reason the India broadcaster has to be checked locally instead of assumed from the NBC logo on a US graphic.</p>
'''

EXTRAS[195] = '''
<h2>A flex, a morning alarm, and a full Sunday underneath</h2>
<p>The NFL can move a Sunday night game in some weeks under its flex rules. Nothing in the prime-time list we used says this Cowboys-Packers kickoff has been flexed. It might never be. If a flex is announced, the 8:20 PM ET figure changes and the 5:50 AM IST figure must change with it. Check NFL.com in the final week rather than laminating the September listing. Until a flex note exists, 8:20 PM ET is the time to publish, with the source named.</p>
<p>Sunday afternoon in the US is a separate slate that ends before this kickoff. Indian viewers who wake up at 5:50 AM are not watching those afternoon games live unless they were up in the middle of the night. Do not describe the Cowboys-Packers result as if it were known on Sunday evening in India. It will not be known until Monday morning. That single timezone fact fixes a whole class of bad recaps. Injury designations follow the league’s Friday-to-Sunday reporting cycle. A Wednesday rumour is not an inactive. Lambeau in mid-October is capable of wind that shows up on kicks; you will see it on the broadcast if it is there. You do not need to predict it in September.</p>
<p>Green Bay is not a neutral site and not Dallas. The home crowd, the frozen-tundra reputation and the actual mid-October weather are three different things, and only the crowd is guaranteed. If you are writing a travel note, the official parking and bag policy for Lambeau Field that week is the document, not a forum post from a January playoff. Kickoff at 8:20 PM local is late for a Wisconsin Sunday and early for a Monday in India. Both descriptions are accurate. Use the one that matches the reader, and put the other in parentheses so nobody argues with the alarm.</p>
'''

EXTRAS[196] = '''
<h2>Pool arithmetic, and the matches that come after</h2>
<p>By Monday afternoon the pool table is the story, and it is a story you should screenshot from the official competition site rather than rebuild from memory of the preview. India’s earlier pool matches against Indonesia, Sri Lanka, Korea and Japan will have produced a record. Bangladesh’s record will be on the same table. A draw can be enough, or not, depending on those rows. This article cannot know the rows on 24 September. On 28 September you can. Update the top of the page with the official table position and leave the 3:30 PM start where it is, because people still search the time while the match is live.</p>
<p>The semi-finals on 1 October and the medal matches on 3 October are real dates in the Hockey India and Indian media schedules, and the participants are not real until the pools finish. A page that says “India play in the semi-final at 1:00 PM” before this Bangladesh match ends is a prediction wearing a fixture’s clothes. Write the knockout dates as dates, and write the opponent as not yet confirmed. Olympic qualification implications, which Hockey India has talked about in the context of Los Angeles 2028, depend on where the team finishes, not on a pool game in isolation. Quote the federation if you explain the pathway. Do not invent a berth.</p>
<p>Japan in late September is still on Japan Standard Time, UTC+9, with no daylight-saving shift to surprise you. The 3-hour-30-minute gap to IST is stable. A viewer who converts 7:00 PM local as 7:00 PM IST will be three and a half hours late and will miss the match. Put both times in the first screen of any graphic: 7:00 PM JST, 3:30 PM IST, Monday 28 September. The cricket quarter-final on the same Games calendar that day is a different clock and a different venue. If your graphic cannot name the sport, do not post it.</p>
'''

EXTRAS[197] = '''
<h2>Tracking one runner instead of the whole field</h2>
<p>Most people who open a marathon page from outside Chicago are trying to find one person. The event’s official tracker uses the bib number. Ask for the bib before Sunday, not at 6:00 PM IST when the corrals are already moving. Wave time matters because a runner in the final wave is not on the course at 7:30 AM local, and a text that says “they started” at 6:00 PM IST may be early by more than an hour. The six-hour-thirty-minute limit NBC Chicago cites is the back of the race, not a target. A runner who starts at 8:35 AM local is on a different clock from the professionals at the front, whose start procedure should be confirmed separately if you are following an elite.</p>
<p>The expo from 8 October is the other date families mix up with race day. It is not a start. If you are travelling, the official participant guide is the list of what you may carry. This article is the list of when the waves move and how that looks in IST, plus a warning that Singapore and Indore are on television at the same time. Pick the runner or pick the cricket. The tracker will still be there if you look up from the T20I at the innings break.</p>
<p>Chicago is UTC−5 that morning, not UTC−6. Using standard time by mistake makes every IST figure an hour early and tells a family in India that the race has started when the corrals are still closed. Write Central Daylight Time in the sentence, not just “Chicago time”. The organiser’s own future-dates page says the listed Sundays can change. If 11 October is ever replaced, the wave clock in this article has to be rebuilt from the new local start, not shifted by a day with the old hour glued on.</p>
'''
