def L(*pairs):
    return list(pairs)

POSTS_8 = []

POSTS_8.append(dict(
    id=176,
    slug="india-vs-uruguay-6-oct-2026-kolkata",
    title="India vs Uruguay 6 Oct 2026: Kolkata Guide",
    metaTitle="India vs Uruguay 6 Oct 2026 — Kolkata, Salt Lake | TheTriFusion",
    excerpt="India host Uruguay on 6 Oct 2026 at Salt Lake Stadium, Kolkata. AIFF confirmed the date. Kick-off minute is not yet federation-confirmed.",
    og1="India vs Uruguay:",
    og2="6 Oct — Kolkata",
    hue=210,
    layout="story",
    tags=["india vs uruguay", "kolkata", "6 october 2026", "salt lake stadium", "football"],
    opener="Three days after Brazil, Kolkata is asked to host another World Cup winner, and the federation’s sentence is shorter than the ticket chatter. On 27 August 2026 the AIFF said Uruguay will play India at the Vivekananda Yuba Bharati Krirangan on 6 October 2026. Uruguay were described as two-time world champions, ranked 20th at the time of that note, with Diego Forlán as head coach, the same Forlán who played for Mumbai City in 2016. Sporting News later listed a 7:00 PM IST kick-off and Sony Sports / SonyLIV. AIFF’s own article does not print a minute. A fixture database has also shown 13:00 UTC, which is 6:30 PM IST. Until the federation or the stadium ticket says one number, the minute is not yet confirmed.",
    verify="Date, venue and opponent: AIFF, 27 August 2026. Coach detail: the same AIFF note names Diego Forlán and the 2016 Mumbai City spell. 7:00 PM IST and Sony Sports / SonyLIV: Sporting News. Conflicting 13:00 UTC listing: FotMob. Broadcast rights also reported by Khel Now as Sony Sports for the Panama, Brazil and Uruguay friendlies. This is not a 2030 World Cup qualifier.",
    time_h2="What is fixed, and what is not",
    rows=L(
        ("Date", "Tuesday, 6 October 2026"),
        ("Venue", "Vivekananda Yuba Bharati Krirangan, Kolkata"),
        ("Listed by Sporting News", "7:00 PM IST"),
        ("Also seen on a fixture database", "13:00 UTC, which is 6:30 PM IST"),
        ("Federation kick-off", "Not yet confirmed in the AIFF announcement"),
        ("Match type", "International friendly"),
        ("Previous match", "India vs Brazil, 3 October, same ground, 7:00 PM IST listed"),
    ),
    time_note="The SportsEvent start on this page uses 7:00 PM IST because that is the consumer listing Sporting News published. If AIFF prints 6:30 PM, move your alarm and treat our schema as out of date until it is edited. We would rather say that in the open than hide the clash.",
    watch_h2="Watching and travelling",
    india="Sony Sports and SonyLIV are the reported home for all three friendlies in this window. Confirm Uruguay as its own tile. Do not assume the Brazil production crew automatically means the same channel number on Tuesday. Khel Now has also said Uruguay tickets were not on sale at the same moment as the Brazil rush. Check District again rather than buying a forwarded screenshot.",
    uk="1:30 PM BST if the 7:00 PM IST listing is right, or 1:00 PM BST if the 6:30 PM listing is right. Another reason not to tell a UK group chat a single minute yet. No UK channel is confirmed here.",
    us="9:30 AM EDT on the 7:00 PM listing, 9:00 AM EDT on the 6:30 PM listing. US carrier not yet confirmed.",
    safety="Official tickets only, whenever they go on sale. No side-door pass. No unofficial stream.",
    sections=[
        ("The week Kolkata actually has", [
            "Saturday is Brazil. Tuesday is Uruguay. Both are at Salt Lake if you believe the two AIFF notes, and you should, on venue and date. The city is not staging them as one festival night. Hotels and trains that look “sold out for Brazil” may still have Tuesday inventory, or they may not. This page will not invent availability. People coming from outside Kolkata should book against the date they can actually attend and keep the other match as television.",
            "Panama on 26 September was in Bengaluru. The squad camp, as reported around Jamil’s 26-man selection, started in Bengaluru and moved to Kolkata on 28 September for the two big friendlies. That is logistics. It is not a predicted lineup. The XI for Uruguay is not yet confirmed, and it may not match the XI that faces Brazil.",
        ]),
        ("Forlán, and the limit of a name", [
            "AIFF pointed out that Uruguay’s coach played in the ISL for Mumbai City in 2016. That is a useful human detail for Indian readers and a poor basis for a tactical preview. Forlán the coach in 2026 is not Forlán the forward in 2016. We will not project a style of play from a ten-year-old club stint. If he speaks in Kolkata, quote the press conference, not a memory.",
            "Uruguay’s two World Cups and a top-20 ranking, as AIFF stated them in August, explain the crowd. They do not explain a score. Friendly results against this level of opponent are not something to dress up as a ranking equation. There is no coupon on this page.",
        ]),
        ("Qualifiers, ISL, and the rest of October", [
            "World Cup 2030 Asian qualifying does not start in this window. The draw for the early AFC rounds has been reported for 15 December 2026, with matches from 2027. Saying “India are in World Cup qualifying this week” is false. Saying “India are playing Uruguay in a friendly the same week the ISL is about to start” is closer. Sportstar has reported an ISL start on 10 October, four days after this match, with the opening fixture still not published in the notice we used. Club football and the national team will overlap in the calendar. They are different competitions.",
            "Schema time 2026-10-06T19:00:00+05:30 is the Sporting News listing, flagged in the intro. The location is the Salt Lake ground. When you share the page, share the caveat with the clock. A clean 7:00 PM graphic with no asterisk will be wrong if the federation chooses 6:30.",
        ]),
    ],
    expect_h2="A cautious plan",
    expect=[
        "Re-check AIFF or the ticket page for the minute during the week of 6 October.",
        "Keep Brazil on Saturday as a separate event.",
        "Expect a different XI from the Brazil game. Not yet confirmed either way.",
        "SonyLIV, confirm the tile.",
        "Do not call it a qualifier.",
    ],
    expect_note="No odds.",
    checks=[
        "Date and ground are confirmed. The minute is not, at federation level.",
        "Hold 6:30 PM and 7:00 PM until one source official to the match repeats itself.",
        "Official tickets only.",
        "Tuesday, not a second Saturday.",
        "Friendly, not a World Cup qualifier.",
    ],
    live_links=L(
        ("/blog/uefa-nations-league-why-trending-explained", "international football in search"),
        ("/blog/liverpool-vs-man-city-11-oct-2026-preview", "the league weekend after this window"),
        ("/blog/arsenal-vs-lille-ucl-13-oct-2026", "a European club page from the same fortnight"),
    ),
    sib_sentence='Brazil on Saturday is <a href="/blog/india-vs-brazil-3-oct-2026-kolkata">the 3 October guide</a>.',
    hub="/web-development",
    hub_label="web development",
    faqs=L(
        ("When is India vs Uruguay?", "Tuesday 6 October 2026 at the Salt Lake Stadium in Kolkata. That date and venue are from the AIFF."),
        ("What time is kick-off?", "Not yet confirmed by the AIFF note. Sporting News lists 7:00 PM IST. Another database has shown 6:30 PM IST. Check again the week of the match."),
        ("Who is Uruguay’s coach?", "Diego Forlán, according to the AIFF announcement, which also notes he played for Mumbai City in 2016."),
        ("Where can India watch?", "Sony Sports and SonyLIV are the reported broadcasters for this set of friendlies. Confirm the EPG."),
        ("Is it a World Cup qualifier?", "No. It is a friendly."),
        ("Is the lineup out?", "Not yet confirmed."),
    ),
    close="Trust the AIFF for the day and the ground. Trust a kick-off minute only when the federation or the official ticket repeats it.",
    event=dict(
        type="SportsEvent",
        name="India vs Uruguay",
        startDate="2026-10-06T19:00:00+05:30",
        organizer="All India Football Federation",
        location=dict(name="Vivekananda Yuba Bharati Krirangan", addressLocality="Kolkata", addressCountry="IN"),
    ),
))

POSTS_8.append(dict(
    id=177,
    slug="isl-2026-27-season-start-10-october",
    title="ISL 2026-27 Season Start: 10 October Guide",
    metaTitle="ISL 2026-27 Starts 10 October — What Is Confirmed | TheTriFusion",
    excerpt="The ISL 2026-27 season is reported to start on 10 October 2026. Clubs, format and play-offs are outlined. The opening fixture is not yet confirmed.",
    og1="ISL 2026-27 Season:",
    og2="Starts 10 October",
    hue=130,
    layout="story",
    tags=["isl 2026-27", "indian super league", "10 october 2026", "indian football", "football"],
    opener="Indian club football’s restart has a date in the reporting and a blank where the first whistle should be. Sportstar, citing the announcement of the new club-led season, says the Indian Super League 2026-27 begins on 10 October 2026 and runs through May 2027, with 163 matches and a return of the play-off, the top six clubs competing for the ISL Cup. The AIFF’s 19 August note had locked 13 clubs and a home-and-away league, and had said the kick-off date and the fixtures would follow. They have partly followed. A start date is now in the Sportstar report. A named opening match, a kick-off time and a broadcaster are not yet confirmed on the documents this guide will stand behind.",
    verify="Sportstar: season starts 10 October 2026, runs to May 2027, 163 matches, play-offs return, top six for the ISL Cup, 13 clubs listed. AIFF, 19 August 2026: 13 clubs, double round-robin home-and-away, kick-off date “in due course”, fixtures in a later note. Opening fixture, venue of match one, and the broadcast partner: not yet confirmed here. Do not use unofficial fixture grids that invent a Kolkata derby on opening night.",
    time_h2="The only time that is fair to print",
    rows=L(
        ("Reported start", "10 October 2026"),
        ("Reported end", "May 2027"),
        ("Matches", "163, per Sportstar"),
        ("Format", "Home-and-away, then play-offs for the top six"),
        ("Opening kick-off", "Not yet confirmed"),
        ("Opening fixture", "Not yet confirmed"),
        ("Broadcaster", "Not yet confirmed"),
    ),
    time_note="Because no first whistle has been published in the sources above, this page does not invent a 7:30 PM IST start. The SportsEvent date is the calendar day 10 October 2026. When the league names a match and a minute, that is the moment to add a clock.",
    watch_h2="How to follow the start legally",
    india="The broadcast partner is not yet confirmed. Earlier in the year the start was discussed alongside a search for a media deal, which is why a channel bug from 2024 or 2025 should not be copied onto this season. When AIFF or the clubs name an app, use that app. Until then, “where to watch ISL” is an unanswered question, not a hidden link.",
    uk="There is no confirmed UK feed for the opening weekend. Indian Super League coverage outside India is sporadic. Check closer to 10 October. Do not assume a Premier League channel will simulcast it.",
    us="No confirmed US kick-off or network, because there is no confirmed opening match. Time zones can wait.",
    safety="An unofficial “live ISL” stream on opening weekend is a good way to install something you did not want. Wait for the rights holder.",
    sections=[
        ("The 13 clubs Sportstar listed", [
            "The clubs named in the Sportstar report are Bengaluru FC, Chennaiyin FC, Churchill Brothers FC, East Bengal FC, FC Goa, Inter Kashi FC, Kerala Blasters FC, Mohun Bagan Super Giant, Mumbai City FC, NorthEast United FC, Odisha FC, Punjab FC and Sporting Club Delhi. That is the list to plan around until the league says otherwise. Derbies people will search — Kolkata’s East Bengal and Mohun Bagan, Kerala against the established sides, Goa — do not have published dates in the announcement this article uses. Wanting a derby is not the same as knowing when it is.",
            "AIFF in August was explicit that fixtures would be a separate communication. Any site that already prints “10 October, 7:30 PM, East Bengal vs Mohun Bagan” is ahead of the document. Treat that grid as not confirmed. We are not repeating it.",
        ]),
        ("What “club-led” changes for a supporter", [
            "The reporting describes a season in which clubs hold commercial rights and the AIFF keeps administrative oversight. For a fan that shows up as sponsorships, ticket sellers and possibly a new broadcast app, not as a change to the shape of a football match. The sporting shape Sportstar describes is the familiar one: everyone plays everyone home and away, then a top-six play-off for the ISL Cup. 163 matches is the volume they gave. We have not re-derived that number from a fixture list, because the fixture list is not public in the sources above. Quote Sportstar, or wait.",
            "One earlier Sportstar piece called East Bengal the defending champion. If you need the official holder of the 2025-26 title, check the league’s own page rather than a chain of reports. This guide does not rest a trophy claim on a single adjective.",
        ]),
        ("How this week sits next to the national team", [
            "India’s friendlies against Brazil (3 October) and Uruguay (6 October) are in Kolkata immediately before the reported ISL start. Players who are with the national team may or may not be released in time for a 10 October club match. That depends on the fixture list, which is not out, and on the coaches, who have not named club XIs. The honest line is that the national-team window and the league start are adjacent. The consequence for any one club is not yet confirmed.",
            "If you publish club sites or a league CMS, leave the opening-day module empty until the PDF exists, and ship the season explainer anyway. A page that says “start date 10 October, opener not yet confirmed” is more useful than a page that guesses Mohun Bagan’s opponent. TheTriFusion builds that kind of calendar for sports and retail clients who would rather update a field than apologise for a fake kick-off. The schema here is dated 2026-10-10 with location “India”, because pinning a city would be a guess.",
        ]),
    ],
    expect_h2="What to do between now and 10 October",
    expect=[
        "Watch for an AIFF or league fixture PDF, not a fan blog grid.",
        "Note the 13 clubs, and ignore a 14th until it is official.",
        "Keep Brazil and Uruguay as national-team events, separate from the ISL.",
        "Do not buy a “season pass” from an app that is not the confirmed broadcaster.",
        "Add a kick-off only when a match has a name and a minute.",
    ],
    expect_note="No odds, no invented opener, no invented score.",
    checks=[
        "10 October 2026 is the reported start, not a confirmed first whistle.",
        "163 matches and a top-six play-off are Sportstar’s figures. Re-read them if the league PDF differs.",
        "Broadcaster not yet confirmed.",
        "No Kolkata derby is confirmed for opening night by this guide.",
        "Friendly internationals that week are a different competition.",
    ],
    live_links=L(
        ("/blog/uefa-nations-league-why-trending-explained", "how competition names get searched"),
        ("/blog/man-united-vs-tottenham-10-oct-2026-preview", "the same Saturday in the Premier League"),
        ("/blog/arsenal-vs-lille-ucl-13-oct-2026", "European football the following week"),
    ),
    sib_sentence='The national team’s Kolkata friendlies are <a href="/blog/india-vs-brazil-3-oct-2026-kolkata">India vs Brazil</a> and <a href="/blog/india-vs-uruguay-6-oct-2026-kolkata">India vs Uruguay</a>.',
    hub="/services/digital-marketing",
    hub_label="digital marketing",
    faqs=L(
        ("When does the ISL 2026-27 season start?", "10 October 2026, according to Sportstar’s report of the league announcement. The opening match is not yet confirmed."),
        ("How many teams?", "13 clubs are listed in that report, matching the AIFF’s August confirmation of a 13-club league."),
        ("What is the format?", "A home-and-away league, then play-offs. Sportstar says the top six contest the ISL Cup and that 163 matches will be played."),
        ("Who broadcasts it?", "Not yet confirmed on this page."),
        ("Is the opening game a Kolkata derby?", "Not yet confirmed. Do not trust a fixture list that names one without a league document."),
        ("Does this clash with India vs Brazil?", "Brazil are on 3 October and Uruguay on 6 October. The reported ISL start is 10 October. They are different competitions."),
    ),
    close="Mark 10 October as the week Indian club football is due back. Mark the first kick-off only when the league names it.",
    event=dict(
        type="SportsEvent",
        name="Indian Super League 2026-27 season start",
        startDate="2026-10-10",
        organizer="All India Football Federation",
        location=dict(name="India", addressLocality="India", addressCountry="IN"),
    ),
))
